<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Liq5Lq6566A5LuL');
$cfg_Cs[2]=array(0,1,1,'5YGl6Lqr5LiW55WM');
$cfg_Cs[3]=array(0,1,1,'57yW56iL5LiW55WM');
$cfg_Cs[4]=array(2,1,1,'5YeP6ISC5LiT5qCP');
$cfg_Cs[5]=array(2,1,1,'5aKe6IKM5LiT5qCP');
$cfg_Cs[6]=array(2,1,1,'56iL5bqP5ZGY5LiT5qCP');
$cfg_Cs[7]=array(3,1,1,'cGhw5ZCO56uv56+H');
$cfg_Cs[8]=array(3,1,1,'5a6e55So5bel5YW356+H');
$cfg_Cs[9]=array(3,1,1,'5byA5Y+R5a6e5oiY56+H');
$cfg_Cs[10]=array(2,1,1,'54m55q6K5Lq6576k');
$cfg_Cs[11]=array(3,1,1,'5YW25LuW6K+t6KiA56+H');
?>