<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YGl6Lqr5LiW55WM');
$cfg_Cs[2]=array(0,1,1,'56iL5bqP5LiW55WM');
$cfg_Cs[3]=array(0,1,1,'5Liq5Lq6566A5LuL');
$cfg_Cs[4]=array(1,1,1,'5oiR6KaB5YeP6ISC');
$cfg_Cs[5]=array(1,1,1,'5oiR6KaB5aKe6IKM');
$cfg_Cs[6]=array(1,1,1,'5oiR6KaB5L+d5YGl');
$cfg_Cs[7]=array(2,1,1,'cGhw');
$cfg_Cs[8]=array(2,1,1,'bXlzcWw=');
$cfg_Cs[9]=array(2,1,1,'amF2YQ==');
$cfg_Cs[10]=array(2,1,1,'5YmN56uv');
?>