<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("title","",77,91);
$z[2]=Array("writer","",137,152);
$z[3]=Array("typeid","",180,232);
$z[3][4]['function']="getTypenameByTypeid(@me)";
$z[4]=Array("click","",272,286);
$z[5]=Array("source","",333,348);
$z[6]=Array("description","",383,403);
$z[7]=Array("arcurl","",412,427);
$z[8]=Array("litpic","",525,540);
$z[9]=Array("senddate","",584,628);
$z[9][4]['function']="date(\"Y-m-d\",@me)";

?>