<div class="newblog">
        <ul>
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <div class="autor"><span>[field:writer/]</span>
		  <span>分类：[field:typeid function="getTypenameByTypeid(@me)" /]</span>
		  <span>浏览（<a href="/">[field:click/]</a>）</span>
		  <span>来源（<a href="/">[field:source/]</a>）</span></div>
          <p>[field:description/]<a href="[field:arcurl/]" target="_blank" class="readmore">全文</a></p>
		  
        </ul>
        <figure><img src="[field:litpic/]" ></figure>
        <div class="dateview">[field:senddate function=date("Y-m-d",@me)/]</div>
      </div>