<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("title","",77,91);
$z[2]=Array("writer","",137,152);
$z[3]=Array("typeid","",180,195);
$z[4]=Array("typeid","",208,223);
$z[5]=Array("click","",256,270);
$z[6]=Array("source","",317,332);
$z[7]=Array("description","",367,387);
$z[8]=Array("arcurl","",396,411);
$z[9]=Array("litpic","",509,524);
$z[10]=Array("senddate","",568,612);
$z[10][4]['function']="date(\"Y-m-d\",@me)";

?>