<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("title","",77,91);
$z[2]=Array("writer","",137,152);
$z[3]=Array("typeid","",180,232);
$z[3][4]['function']="getTypenameByTypeid(@me)";
$z[4]=Array("typeid","",245,260);
$z[5]=Array("click","",293,307);
$z[6]=Array("source","",354,369);
$z[7]=Array("description","",404,424);
$z[8]=Array("arcurl","",433,448);
$z[9]=Array("litpic","",546,561);
$z[10]=Array("senddate","",605,649);
$z[10][4]['function']="date(\"Y-m-d\",@me)";

?>