<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("title","",77,91);
$z[2]=Array("writer","",137,152);
$z[3]=Array("listtype","",180,197);
$z[4]=Array("typeid","",210,225);
$z[5]=Array("click","",258,272);
$z[6]=Array("source","",319,334);
$z[7]=Array("description","",369,389);
$z[8]=Array("arcurl","",398,413);
$z[9]=Array("litpic","",511,526);
$z[10]=Array("senddate","",570,614);
$z[10][4]['function']="date(\"Y-m-d\",@me)";

?>