<h2 class="c_titile">[field:title /]</h2>
      <p class="box_c"><span class="d_time">发布时间：{dede:field.pubdate function="MyDate('Y-m-d H:i',@me)"/}</span><span>作者：{dede:field.writer/}</span><span>浏览:<script src="{dede:field name='phpurl'/}/count.php?view=yes&aid={dede:field name='id'/}&mid={dede:field name='mid'/}" type='text/javascript' language="javascript"></script>次</span><span>来源:{dede:field.source /}</span></p>

         [field.body /] <br>
 [field:body /]<br>