<div class="blogs">
        <h3><a href="/">[field:title/]</a></h3>
        <figure><img src="[field:litpic/]" ></figure>
        <ul>
          <p>[field:description/]</p>
          <a href="/" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
        </ul>
        <p class="autor"><span>作者：[field:write/]</span><span>分类：【<a href="/">[field:typeid/]</a>】</span><span>浏览（<a href="/">[field:click/]</a>）</span><span>来源（<a href="/">[field:source/]</a>）</span></p>
        <div class="dateview">[field:senddate/]</div>
      </div>