<?php
$z[0]=Array("arcurl","",60,75);
$z[1]=Array("title","",77,91);
$z[2]=Array("writer","",137,152);
$z[3]=Array("typeid","",180,232);
$z[3][4]['function']="getTypenameByTypeid(@me)";
$z[4]=Array("click","",270,284);
$z[5]=Array("source","",327,342);
$z[6]=Array("description","",375,395);
$z[7]=Array("arcurl","",404,419);
$z[8]=Array("litpic","",517,532);
$z[9]=Array("senddate","",576,620);
$z[9][4]['function']="date(\"Y-m-d\",@me)";

?>