<?php
$z[0]=Array("arcurl","",42,57);
$z[1]=Array("title","",59,73);
$z[2]=Array("litpic","",110,125);
$z[3]=Array("description","",166,186);
$z[4]=Array("arcurl","",211,226);
$z[5]=Array("writer","",326,341);
$z[6]=Array("typeid","",378,393);
$z[7]=Array("click","",434,448);
$z[8]=Array("source","",489,504);
$z[9]=Array("senddate","",554,571);
$z[10]=Array("pubdate","",591,661);
$z[10][4]['function']="strftime(\"%A on %b %d, %Y, %X\",1454517842)";

?>