<div class="newblog">
        <ul>
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <div class="autor"><span>[field:writer/]</span>
		  <span>分类：[field:typeid function="getTypenameByTypeid(@me)" /]</span>
		  <span>浏览（<a href="/">[field:click/]</a>）</span>
		  <span>来源（<a href="/">[field:source/]</a>）</span></div>
          <p>十一月中旬开始，排名突然下降了，网站“个人博客”关键词排名从第一页第二名滑落到100页以后了，个人博客这个关键词百度已经搜不到了，仅有google、搜狗... <a href="/" target="_blank" class="readmore">全文</a></p>
		  
        </ul>
        <figure><img src="images/001.jpg" ></figure>
        <div class="dateview">2014-04-08</div>
      </div>