<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",347,377);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",414,441);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",459,491);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",537,569);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",616,648);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",806,838);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("channel","\r\n	<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n	",1110,1211);
$z[8][4]['type']="top";
$z[8][4]['row']="8";
$z[9]=Array("arclist","\r\n      <div class=\"blogs\">\r\n        <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n        <figure><img src=\"[field:litpic/]\" ></figure>\r\n        <ul>\r\n          <p>[field:description/]</p>\r\n          <a href=\"[field:arcurl/]\" class=\"readmore\">阅读全文&gt;&gt;</a>\r\n        </ul>\r\n        <p class=\"autor\"><span>作者：[field:writer/]</span><span>分类：【<a href=\"/\">[field:typeid/]</a>】</span><span>浏览（<a href=\"/\">[field:click/]</a>）</span><span>来源（<a href=\"/\">[field:source/]</a>）</span></p>\r\n        <div class=\"dateview\">[field:senddate/]</div>\r\n      </div>\r\n	  ",1594,2245);
$z[9][4]['channelid']="1";
$z[9][4]['row']="5";
$z[10]=Array("global","",5045,5077);
$z[10][4]['name']="cfg_templets_skin";

?>