<?php
$z[0]=Array("channel","\r\n	      <li class=\"rnav[field:global name=autoindex runphp='yes']@me=@me+1;[/field:global]\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n		",37,234);
$z[0][4]['type']="son";
$z[0][4]['row']="4";
$z[1]=Array("arclist","\r\n        <li><span class=\"num[field:global.autoindex/]\">[field:global.autoindex/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n	  ",357,564);
$z[1][4]['channelid']="1";
$z[1][4]['row']="5";
$z[1][4]['orderby']="click";
$z[2]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n		",651,795);
$z[2][4]['channelid']="1";
$z[2][4]['row']="5";
$z[2][4]['flag']="c";
$z[2][4]['orderby']="pubdate";

?>